### PR TITLE
Fixed redundant spacing when using fast_fail option

### LINKED ISSUE #158: fast_fail option causes redundant newlines for skipped tests.
Output when using fast_fail options with skipped tests prints out redundant newlines.  For example:

```ruby
# Running tests with run options --seed 58301:

..............S....................S.........................................SSSSSSSSSSSSSSSS..

Finished tests in 22.954128s, 4.1387 tests/s, 7.1447 assertions/s.




















95 tests, 164 assertions, 0 failures, 0 errors, 18 skips
```

Looks like the newline in the default reporter is out of place.  Also, `message_for` should probably allow for empty messages so that it can be easily overridden without redundant newlines.  I've patched it so the new output looks as follows:

```ruby
# Running tests with run options --seed 5569:

.............S....................S.........................................SSSSSSSSSSSSSSSS...

Finished tests in 23.166914s, 4.1007 tests/s, 7.0791 assertions/s.


95 tests, 164 assertions, 0 failures, 0 errors, 18 skips
```

PR to follow.

### PR DESCRIPTION
**Pull request by ojak**
Output when using fast_fail options with skipped tests prints out redundant newlines.  For example:

```ruby
# Running tests with run options --seed 58301:

..............S....................S.........................................SSSSSSSSSSSSSSSS..

Finished tests in 22.954128s, 4.1387 tests/s, 7.1447 assertions/s.




















95 tests, 164 assertions, 0 failures, 0 errors, 18 skips
```

Looks like the newline in the default reporter is out of place.  Also, `message_for` should probably allow for empty messages so that it can be easily overridden without redundant newlines.  I've patched it so the new output looks as follows:

```ruby
# Running tests with run options --seed 5569:

.............S....................S.........................................SSSSSSSSSSSSSSSS...

Finished tests in 23.166914s, 4.1007 tests/s, 7.0791 assertions/s.


95 tests, 164 assertions, 0 failures, 0 errors, 18 skips
```

### CODE REVIEW

File: lib/minitest/reporters/default_reporter.rb [hunk 1]
```diff
@@ -124,7 +124,11 @@ def report
       alias to_s report
 
       def print_failure(test)
-        puts colored_for(result(test), message_for(test))
+        message = message_for(test)
+        unless message.nil? || message.strip == ''
+          puts colored_for(result(test), message_for(test))
```
Comment (os97673) [inline lib/minitest/reporters/default_reporter.rb]: perhaps you want to use `message` instead of `message_for(test)` here ;)

**Comment by os97673** [comment]
It would be nice to see output of the reporter when we have a least one failure

**Comment by ojak** [comment]
Oops, lol.  done.

File: lib/minitest/reporters/default_reporter.rb (hunk 1 above)
Comment (ojak) [inline lib/minitest/reporters/default_reporter.rb]: Oops, lol. done.

**Comment by ojak** [comment]
Here's the final output:

`{ fast_fail: true, detailed_skip: false }`
```
.....F
Failure:
MyTest#test_six [/Users/.../my_test.rb:10]
Minitest::Assertion: Failed assertion, no message given.
........S.......F...
```
----
`{ fast_fail: true, detailed_skip: true }`
```
.....F
Failure:
MyTest#test_six [/Users/.../my_test.rb:10]
Minitest::Assertion: Failed assertion, no message given.
........S
Skipped:
MyTest#test_fourteen [/Users/.../my_test.rb:15]:
Skip me.
......
```
----
`{ fast_fail: false }`
```
.....F........S...
```

**Comment by os97673** [comment]
Thank you for the contribution.
