### PR TITLE
Make sure our Minitest plugin initializes last.

### LINKED ISSUE #230: Rails 5.1.3 display regression
Hello.

Checking Rails 5.1.3.rc3 against our main application, and I find display quite broken while executing tests. I formatted output from my terminal (adding LF and removing extra spaces to fit here in the issue), it seems that default reporter still run even with Rails trick from README (Minitest::Reporters.use! Minitest::Reporters::ProgressReporter.new, ENV, Minitest.backtrace_filter`

```
❯ rails test
Started with run options --seed 34013

Run options: --seed 34013-=---=---=---=---=---=---=-] 0% Time: 00:00:00,  ETA: ??:??:??

# Running:


.  2756/2: [                                         ] 0% Time: 00:00:02,  ETA: 00:56:0
.  2756/3: [                                         ] 0% Time: 00:00:02,  ETA: 00:37:3
...  2756/6: [                                         ] 0% Time: 00:00:02,  ETA: 00:18
.  2756/7: [                                         ] 0% Time: 00:00:02,  ETA: 00:15:5
.  2756/8: [                                         ] 0% Time: 00:00:02,  ETA: 00:14:0
..  2756/10: [                                        ] 0% Time: 00:00:02,  ETA: 00:12
:..  2756/12: [                                        ] 0% Time: 00:00:02,  ETA: 00:10
:.  2756/13: [                                        ] 0% Time: 00:00:02,  ETA: 00:10:1
.  2756/14: [                                        ] 0% Time: 00:00:03,  ETA: 00:09:5
.  2756/15: [                                        ] 0% Time: 00:00:03,  ETA: 00:09:5
.  2756/16: [                                        ] 0% Time: 00:00:03,  ETA: 00:09:4
.  2756/17: [                                        ] 0% Time: 00:00:03,  ETA: 00:09:3
.  2756/18: [                                        ] 0% Time: 00:00:03,  ETA: 00:09:0
...  2756/21: [                                        ] 0% Time: 00:00:03,  ETA: 00:07
......^CInterrupted. Exiting...
  2756/2756: [=====================================] 100% Time: 00:00:03, Time: 00:00:03

Finished in 3.71382s
26 tests, 81 assertions, 0 failures, 0 errors, 0 skips


Finished in 3.713659s, 7.0012 runs/s, 21.8114 assertions/s.
26 runs, 81 assertions, 0 failures, 0 errors, 0 skips
```

I have no idea how things work so I only report to keep track of it.
It will eventually be resolved after Rails 5.1.3 final release, or may be it simply a minitest bug?

### PR DESCRIPTION
**Pull request by samcday**
This ensures that our changes to Minitest.reporters are not trampled by other
Minitest plugins, like the core Rails Minitest plugin that was introduced in
Rails 5.

Fixes #230

### CODE REVIEW

**Comment by professorNim** [comment]
+1, holding back from Rails 5.1.3 for this very reason

File: lib/minitest/reporters.rb [hunk 1]
```diff
@@ -30,6 +30,11 @@ def self.use!(console_reporters = ProgressReporter.new, env = ENV, backtrace_fil
       Minitest.backtrace_filter = backtrace_filter unless backtrace_filter.nil?
 
       unless defined?(@@loaded)
+        # Ensure that minitest-reporters is initialized last, so that our patches to Minitest.reporters are not
+        # trampled by other Minitest plugins, like the core Rails 5 Minitest plugin.
+        Minitest.load_plugins
```
Comment (os97673) [inline lib/minitest/reporters.rb]: what if plugins were already loaded?

Comment (samcday) [reply lib/minitest/reporters.rb]: Minitest don't care: https://github.com/seattlerb/minitest/blob/master/lib/minitest.rb#L86

Comment (os97673) [reply lib/minitest/reporters.rb]: Ok, let's try this.

**Comment by markedmondson** [comment]
I'm still seeing duplicate output on Rails 5.0.5 which I think was one of the issues from #230 (which was solved with the "workaround"). Eg.

```
Run options: --seed 43372

# Running:

Run options: --seed 43372

# Running:

..

Finished in 4.454743s, 0.2245 runs/s, 0.0000 assertions/s.

1 runs, 0 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by os97673** [comment]
could you please provide simple test repo so I could play with it.
